[package]
name = "hotkey"
version = "0.3.0"
license = "MIT"
description = "Register global hotkeys"
documentation = "https://docs.rs/hotkey"
repository = "https://github.com/UnwrittenFun/hotkey-rs"
authors = ["James Birtles <jameshbirtles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winuser"] }

[target.'cfg(target_os = "linux")'.dependencies]
x11-dl = "2.18.1"
